# Generated by Django 4.1.4 on 2023-01-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_payment_total_amount_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingstat',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order'),
        ),
    ]
