# Generated by Django 4.1.4 on 2023-01-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_lendingstat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingstat',
            name='loan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='shippingStatus',
            field=models.CharField(blank=True, choices=[('Preparing', 'Preparing'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Ready for Pick Up', 'Ready for Pick Up'), ('Picked Up', 'Picked Up')], max_length=50),
        ),
    ]
