# Generated by Django 4.1.4 on 2023-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_lendingstat_loan_alter_orderdetails_shippingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingstat',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Denied', 'Denied')], max_length=50, null=True),
        ),
    ]
